### ISSUE TITLE
Missing code in gen_syn_dataset.py

### ISSUE THREAD

**Issue by YCaigogogo** [orrzohar/LOVM#5]
Dear author, I found that the synonym dataset file generated using "python modelGPT/generate_syn_dataset.py" cannot be directly used for modelGPT/encode_syn_dataset.py. This is because the input data format expected by modelGPT/encode_syn_dataset.py should be:
“”“ {"AM General Hummer SUV 2000": {"a photo of a {c}.": ["a photo of a vehicle.", "a photo of a SUV.", "a photo of an off-road vehicle.", "a photo of a Hummer."]}} ”“”

However, the actual data generated is in the form of:

“”“{"AM General Hummer SUV 2000": ["1. vehicle", "2. SUV", "3. off-road vehicle", "4. Hummer"]}”“”

It seems that there might be some post-processing steps missing in the generate_syn_dataset.py script.

**Comment by orrzohar** [comment]
Hi @YCaigogogo,
I looked into my old codebase and found this script:

```code
import os
import json
os.makedirs('stripped', exist_ok=True)
with open('../../LOVM/datasets.txt', 'r') as f:
    datasets = [line.rstrip('\n') for line in f.readlines()]
    
for dataset in datasets:
    print(dataset)
    with open(f'{dataset}.json', 'r') as f:
        # Load the JSON data from the file
        data = json.load(f)
        
    with open(f'../../LOVM/templates/{dataset}.txt', 'r') as f:
        templates = [line.rstrip('\n') for line in f.readlines()]   

    for k, v in data.items():
        tmp = [vv for vv in v if len(vv)>4]
        if len(tmp)==1:
            tmp = [vv.split(f'{i+1}. ')[-1] for i, vv in enumerate(tmp[0].split(','))]
        tmp = [vv.split(f'{i+1}. ')[-1] for i, vv in enumerate(tmp)]
        tmp = [vv.split(f'{i}. ')[-1] for i, vv in enumerate(tmp)]
        data[k]={}
        for t in templates:
            data[k][t] = [t.replace('{c}', c) for c in tmp]
        
    with open(f'{dataset}.json', 'w') as f:
        json.dump(data, f)
```

Would you mind looking if this fixes the problem? 
If it does, I will add it to "generate_syn_dataset.py" so in the future, that is produced directly. 
Best,
Orr

**Comment by YCaigogogo** [comment]
Yes, this works. Thank you~
