### ISSUE TITLE
Questions about the process for generating eval_table_features.csv

### ISSUE THREAD

**Issue by YCaigogogo** [orrzohar/LOVM#6]
Hello, I am using **calc_text_features.py** to generate **eval_table_features.csv** and have observed that the computed metrics for **text-f1** and **text-acc1** differ from the original results you provided, while the other metrics remain the same. I suspect this might be due to the influence of sigma in the **eval_on_dataset** function. Could you please explain the reason for adding noise and what the appropriate value for sigma should be?

**Comment by orrzohar** [comment]
Hi @YCaigogogo,
Yes, the "sigma" is very important for -- please see "Figure 8: Ablating Noise Injection Effect on Text Top-1 Accuracy." of the supplementary. Adding noise is very important the text-f1 and text-acc1 to be more correlated with GT (image-based) evaluations. 
I believe the default "sigma" should be what I used -- but will validate on my codebase.
Best,
Orr

**Comment by YCaigogogo** [comment]
Ok，Sorry for lefting out information in supplementary. Thank you very much.

**Comment by orrzohar** [comment]
Hi @YCaigogogo,
I want to make sure this has resolved before closing this,
Best,
Orr

**Comment by YCaigogogo** [comment]
Yes, it has resolved. Thank you very much.
