### ISSUE TITLE
Could you provide your dataset and dataloader files?

### ISSUE THREAD

**Issue by YCaigogogo** [orrzohar/LOVM#7]
Hello, authors. I would like to inquire whether you could open-source the download paths for your processed datasets and dataloaders. I know that these tasks might be something I could undertake myself. However, considering that you might already have processed datasets and dataloaders, and to maintain consistency with the dataset divisions you are using, I would like to ask if you could open-source this benchmark's processed datasets and dataloaders.

**Comment by orrzohar** [comment]
Hi @YCaigogogo,
Could you please explain what you mean? Do you datasets and data loaders for the image datasets? 
Best,
Orr

**Comment by orrzohar** [comment]
Hi @YCaigogogo,
If you mean image-based evaluation - I used the [CLIP_benchmark](https://github.com/LAION-AI/CLIP_benchmark) (this was mentioned in the MS and in the codebase under credits).
Best,
Orr

**Comment by YCaigogogo** [comment]
Yeah I mean image-based evaluation. I'll check out CLIP Benchmark. Thank you!
